Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'action_mailbox_amazon_ingress.gemspec'

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*.rb'
    - 'vendor/**/*'
    - 'spec/support/dummy/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  Enabled: false
